export const GEO_STATS_TARGETS = {
  'buenos-aires': {
    citySlug: 'buenos-aires',
    locality: 'Buenos Aires',
    province: 'Buenos Aires',
    provinceSlug: 'buenos-aires',
    whereSql: '(city = ? OR locality = ?)',
    bindings: ['Buenos Aires', 'Buenos Aires'],
  },
  caba: {
    citySlug: 'caba',
    locality: 'CABA',
    province: 'Buenos Aires',
    provinceSlug: 'buenos-aires',
    whereSql: '(locality IN (?, ?, ?) OR city IN (?, ?, ?))',
    bindings: [
      'CABA',
      'Ciudad Autónoma de Buenos Aires',
      'Capital Federal',
      'CABA',
      'Ciudad Autónoma de Buenos Aires',
      'Capital Federal',
    ],
  },
  'buenos-aires-provincia': {
    citySlug: 'buenos-aires-provincia',
    locality: 'Provincia de Buenos Aires',
    province: 'Buenos Aires',
    provinceSlug: 'buenos-aires',
    whereSql: 'city = ?',
    bindings: ['Buenos Aires'],
  },
  cordoba: {
    citySlug: 'cordoba',
    locality: 'Córdoba',
    province: 'Córdoba',
    provinceSlug: 'cordoba',
    whereSql: '(city IN (?, ?) AND locality IN (?, ?, ?))',
    bindings: ['Córdoba', 'Cordoba', 'Capital', 'Córdoba', 'Cordoba'],
  },
  'cordoba-provincia': {
    citySlug: 'cordoba-provincia',
    locality: 'Provincia de Córdoba',
    province: 'Córdoba',
    provinceSlug: 'cordoba',
    whereSql: 'city = ?',
    bindings: ['Córdoba'],
  },
  rosario: {
    citySlug: 'rosario',
    locality: 'Rosario',
    province: 'Santa Fe',
    provinceSlug: 'santa-fe',
    whereSql: '(locality = ? AND city IN (?, ?))',
    bindings: ['Rosario', 'Santa Fe', 'Santa Fé'],
  },
  mendoza: {
    citySlug: 'mendoza',
    locality: 'Mendoza',
    province: 'Mendoza',
    provinceSlug: 'mendoza',
    whereSql: '(city = ? OR locality = ?)',
    bindings: ['Mendoza', 'Mendoza'],
  },
  'la-plata': {
    citySlug: 'la-plata',
    locality: 'La Plata',
    province: 'Buenos Aires',
    provinceSlug: 'buenos-aires',
    whereSql: '(locality = ? AND city = ?)',
    bindings: ['La Plata', 'Buenos Aires'],
  },
  'mar-del-plata': {
    citySlug: 'mar-del-plata',
    locality: 'Mar del Plata',
    province: 'Buenos Aires',
    provinceSlug: 'buenos-aires',
    whereSql: '(locality = ? AND city = ?)',
    bindings: ['Mar del Plata', 'Buenos Aires'],
  },
  'santa-fe': {
    citySlug: 'santa-fe',
    locality: 'Santa Fe',
    province: 'Santa Fe',
    provinceSlug: 'santa-fe',
    whereSql: '(city IN (?, ?) OR locality IN (?, ?))',
    bindings: ['Santa Fe', 'Santa Fé', 'Santa Fe', 'Santa Fé'],
  },
  neuquen: {
    citySlug: 'neuquen',
    locality: 'Neuquén',
    province: 'Neuquén',
    provinceSlug: 'neuquen',
    whereSql: '(city = ? OR locality = ?)',
    bindings: ['Neuquén', 'Neuquén'],
  },
  tucuman: {
    citySlug: 'tucuman',
    locality: 'Tucumán',
    province: 'Tucumán',
    provinceSlug: 'tucuman',
    whereSql: 'city = ?',
    bindings: ['Tucumán'],
  },
  salta: {
    citySlug: 'salta',
    locality: 'Salta',
    province: 'Salta',
    provinceSlug: 'salta',
    whereSql: 'city = ?',
    bindings: ['Salta'],
  },
  corrientes: {
    citySlug: 'corrientes',
    locality: 'Corrientes',
    province: 'Corrientes',
    provinceSlug: 'corrientes',
    whereSql: 'city = ?',
    bindings: ['Corrientes'],
  },
  parana: {
    citySlug: 'parana',
    locality: 'Paraná',
    province: 'Entre Ríos',
    provinceSlug: 'entre-rios',
    whereSql: '(locality = ? AND city = ?)',
    bindings: ['Paraná', 'Entre Ríos'],
  },
  bahiablanca: {
    citySlug: 'bahiablanca',
    locality: 'Bahía Blanca',
    province: 'Buenos Aires',
    provinceSlug: 'buenos-aires',
    whereSql: '(locality = ? AND city = ?)',
    bindings: ['Bahía Blanca', 'Buenos Aires'],
  },
  'san-juan': {
    citySlug: 'san-juan',
    locality: 'San Juan',
    province: 'San Juan',
    provinceSlug: 'san-juan',
    whereSql: 'city = ?',
    bindings: ['San Juan'],
  },
  'san-luis': {
    citySlug: 'san-luis',
    locality: 'San Luis',
    province: 'San Luis',
    provinceSlug: 'san-luis',
    whereSql: 'city = ?',
    bindings: ['San Luis'],
  },
  'rio-cuarto': {
    citySlug: 'rio-cuarto',
    locality: 'Río Cuarto',
    province: 'Córdoba',
    provinceSlug: 'cordoba',
    whereSql: '(locality = ? AND city = ?)',
    bindings: ['Río Cuarto', 'Córdoba'],
  },
  posadas: {
    citySlug: 'posadas',
    locality: 'Posadas',
    province: 'Misiones',
    provinceSlug: 'misiones',
    whereSql: '(locality = ? AND city = ?)',
    bindings: ['Posadas', 'Misiones'],
  },
  jujuy: {
    citySlug: 'jujuy',
    locality: 'Jujuy',
    province: 'Jujuy',
    provinceSlug: 'jujuy',
    whereSql: 'city = ?',
    bindings: ['Jujuy'],
  },
  'entre-rios': {
    citySlug: 'entre-rios',
    locality: 'Entre Ríos',
    province: 'Entre Ríos',
    provinceSlug: 'entre-rios',
    whereSql: 'city = ?',
    bindings: ['Entre Ríos'],
  },
  'rio-negro': {
    citySlug: 'rio-negro',
    locality: 'Río Negro',
    province: 'Río Negro',
    provinceSlug: 'rio-negro',
    whereSql: 'city = ?',
    bindings: ['Río Negro'],
  },
  chaco: {
    citySlug: 'chaco',
    locality: 'Chaco',
    province: 'Chaco',
    provinceSlug: 'chaco',
    whereSql: 'city = ?',
    bindings: ['Chaco'],
  },
  'santa-cruz': {
    citySlug: 'santa-cruz',
    locality: 'Santa Cruz',
    province: 'Santa Cruz',
    provinceSlug: 'santa-cruz',
    whereSql: 'city = ?',
    bindings: ['Santa Cruz'],
  },
  misiones: {
    citySlug: 'misiones',
    locality: 'Misiones',
    province: 'Misiones',
    provinceSlug: 'misiones',
    whereSql: 'city = ?',
    bindings: ['Misiones'],
  },
};

export const GEO_STATS_SLUGS = Object.keys(GEO_STATS_TARGETS);

export function getGeoStatsTarget(slug) {
  return GEO_STATS_TARGETS[slug] || null;
}
