ALTER TABLE escort_profiles ADD COLUMN price_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE escort_profiles ADD COLUMN currency TEXT NOT NULL DEFAULT 'ARS';
ALTER TABLE escort_profiles ADD COLUMN is_demo INTEGER NOT NULL DEFAULT 0;
